### ISSUE TITLE
Configurable DLL build configuration

### ISSUE THREAD

**Issue by ddormer** [ddormer/valheim-serverside#60]
```
workflow_dispatch:
    inputs:
      build_configuration:
        description: 'Build configuration'
        default: 'Release'
```

```
      run: |
        xcopy /E /I lib ..\ValheimLibs
        xcopy /I serverfiles\valheim_server_Data\Managed\* ..\ValheimLibs\
        if [ -n "${{ github.event.inputs.build_configuration }}" ]
        then
            msbuild /t:Restore,Build -p:Configuration=${{ github.event.inputs.build_configuration }}
        else
            msbuild /t:Restore,Build -p:Configuration=Release
        fi
```
